import { v4 as uuid } from "uuid";

export const products = [
  {
    _id: uuid(),
    title: "Indian Punk #065",
    author: "web3 bro",
    description: "some random long long long long long text for now",
    price: "500",
    categoryName: "art",
    trending: true,
    chain: "polygon",
    rating: 4,
    img: "/assets/065_indian.png",
  },
  {
    _id: uuid(),
    title: "Indian Punk #023",
    author: "web3 bro",
    description: "some random long long long long long text for now",
    price: "750",
    categoryName: "art",
    trending: true,
    chain: "polygon",
    rating: 3,
    img: "/assets/023_indian.png"
  },
  {
    _id: uuid(),
    title: "Indian Punk #043",
    author: "web3 bro",
    description: "some random long long long long long text for now",
    price: "399",
    categoryName: "art",
    trending: false,
    chain: "polygon",
    rating: 5,
    img: "/assets/043_indian.png"
  },
  {
    _id: uuid(),
    title: "Thug Elon #1771",
    author: "Space Party",
    description: "some random long long long long long text for now",
    price: "899",
    categoryName: "celebrity",
    trending: false,
    chain: "ethereum",
    rating: 4,
    img: "/assets/1771_elon.jpg"
  },
  {
    _id: uuid(),
    title: "Thug Elon #2195",
    author: "Space Party",
    description: "some random long long long long long text for now",
    price: "1499",
    categoryName: "celebrity",
    trending: true,
    chain: "ethereum",
    rating: 5,
    img: "/assets/2195_elon.jpg"
  },
  {
    _id: uuid(),
    title: "Thug Elon #2141",
    author: "Space Party",
    description: "some random long long long long long text for now",
    price: "800",
    categoryName: "celebrity",
    trending: false,
    chain: "ethereum",
    rating: 4,
    img: "/assets/2141_elon.jpg"
  },
  {
    _id: uuid(),
    title: "Thug Elon #1189",
    author: "Space Party",
    description: "some random long long long long long text for now",
    price: "1100",
    categoryName: "celebrity",
    trending: false,
    chain: "ethereum",
    rating: 2,
    img: "/assets/1189_elon.jpg"
  },
  {
    _id: uuid(),
    title: "Bollywood wala Gabbar",
    author: "BollyDev",
    description: "some random long long long long long text for now",
    price: "450",
    categoryName: "bollywood",
    trending: false,
    chain: "polygon",
    rating: 5,
    img: "/assets/gabbar.png"
  },
  {
    _id: uuid(),
    title: "Thakur's Dream",
    author: "BollyDev",
    description: "some random long long long long long text for now",
    price: "1200",
    categoryName: "bollywood",
    trending: true,
    chain: "polygon",
    rating: 4,
    img: "/assets/thakur_dream.png"
  },
  {
    _id: uuid(),
    title: "Basanti",
    author: "BollyDev",
    description: "some random long long long long long text for now",
    price: "750",
    categoryName: "bollywood",
    trending: false,
    chain: "polygon",
    rating: 5,
    img: "/assets/basanti.png"
  },
  {
    _id: uuid(),
    title: "Ape Yatch Club 2577",
    author: "Ape King",
    description: "some random long long long long long text for now",
    price: "450",
    categoryName: "ticket",
    trending: true,
    chain: "ethereum",
    rating: 4,
    img: "/assets/2577_bored.png"
  },
  {
    _id: uuid(),
    title: "Ape Yatch Club 5465",
    author: "Ape King",
    description: "some random long long long long long text for now",
    price: "700",
    categoryName: "ticket",
    trending: false,
    chain: "ethereum",
    rating: 1,
    img: "/assets/5465_bored.png"
  },
  {
    _id: uuid(),
    title: "Ape Yatch Club 4671",
    author: "Ape King",
    description: "some random long long long long long text for now",
    price: "550",
    categoryName: "ticket",
    trending: false,
    chain: "ethereum",
    rating: 4,
    img: "/assets/4671_bored.png"
  },
  {
    _id: uuid(),
    title: "Ape Yatch Club 8337",
    author: "Ape King",
    description: "some random long long long long long text for now",
    price: "700",
    categoryName: "ticket",
    trending: false,
    chain: "ethereum",
    rating: 3,
    img: "/assets/8337_bored.png"
  },
  {
    _id: uuid(),
    title: "Asics Metaracer",
    author: "Asics",
    description: "some random long long long long long text for now",
    price: "999",
    categoryName: "sports",
    trending: false,
    chain: "ethereum",
    rating: 4,
    img: "/assets/metaracer.jpeg"
  },
  {
    _id: uuid(),
    title: "Asics Metaspeed Sky",
    author: "Asics",
    description: "some random long long long long long text for now",
    price: "699",
    categoryName: "sports",
    trending: false,
    chain: "ethereum",
    rating: 4,
    img: "/assets/metaspeed.jpg"
  },
  {
    _id: uuid(),
    title: "Asics Metarise",
    author: "Asics",
    description: "some random long long long long long text for now",
    price: "900",
    categoryName: "sports",
    trending: true,
    chain: "ethereum",
    rating: 5,
    img: "/assets/metarise.jpg"
  },
];
