export { getSortedProducts } from './sortedData.js'
export { getFilteredData } from './filteredData'
export { filterByCategory } from './filterByCategory.js'
export { filterByChain } from './filterByChain.js'
export { filterByRating } from './filterByRating.js'